[project]
name = "chatbot-model"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lightning>=2.5.0.post0",
    "pytorch-lightning>=2.5.0.post0",
    "torch>=2.6.0",
    "transformers>=4.48.2",
]
